# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Sentera6XProcessing
                                 A QGIS plugin
 This plugin processes mosaics created using Sentera 6X imagery.  Outputs include a 5-band moasic and index layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-11
        copyright            : (C) 2021 by Sentera
        email                : gis@sentera.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Sentera6XProcessing class from file Sentera6XProcessing.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sentera_6x_processing import Sentera6XProcessing
    return Sentera6XProcessing(iface)
